# See https://aka.ms/yaml

trigger:
  - develop

pool:
  name: NodeJS
  demands: npm

steps:
  - task: Npm@1
    displayName: 'npm ci'
    inputs:
      command: custom
      customCommand: ci

  - task: Npm@1
    displayName: 'npm lint'
    inputs:
      command: custom
      customCommand: 'run lint'

  - task: Npm@1
    displayName: 'npm test'
    inputs:
      command: custom
      customCommand: 'run test -- --watch=false --browsers=ChromeHeadlessNoSandbox'

  - task: Npm@1
    displayName: 'npm build'
    inputs:
      command: custom
      customCommand: 'run build'

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: dist
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      CleanTargetFolder: true
      OverWrite: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: agri-gaia-platform'
    inputs:
      ArtifactName: 'agri-gaia-platform'
